export enum RouteUrls {
  AddAccount = '/sign-in/add-account',
  AddNetwork = '/add-network',
  ChooseAccount = '/connect/choose-account',
  Home = '/',
  Installed = '/',
  PopupHome = '/',
  Receive = '/receive',
  Send = '/send',
  Buy = '/buy',
  RecoveryCode = '/sign-in/recover',
  SetPassword = '/set-password',
  SettingsKey = '/settings/secret-key',
  SignIn = '/sign-in',
  SignInInstalled = '/installed/sign-in',
  SignOutConfirm = '/sign-out',
  SignUp = '/sign-up',
  Transaction = '/transaction',
  Username = '/username',
}
