export enum OnboardingSelectors {
  AnalyticsAllowBtn = 'analytics-allow-btn',
  AnalyticsDenyBtn = 'analytics-deny-btn',
  BackUpSecretKeyBtn = 'back-up-secret-key-btn',
  ConfirmPasswordInput = 'confirm-password-input',
  HideStepsBtn = 'hide-steps-btn',
  HiroWalletLogoRouteToHome = 'hiro-wallet-logo-route-to-home',
  NewPasswordInput = 'set-or-enter-password-input',
  NoAssetsFundAccountLink = 'no-assets-fund-account-link',
  SecretKey = 'secret-key',
  SetPasswordBtn = 'set-password-btn',
  SignInLink = 'sign-in-link',
  SignInBtn = 'sign-in-btn',
  SignUpBtn = 'sign-up-btn',
  StepItemDone = 'step-item-done',
  StepItemStart = 'step-item-start',
  StepsList = 'steps-list',
}
