export enum SettingsSelectors {
  ToggleTheme = 'change-theme',
  GetSupport = 'get-support',
  MenuBtn = 'menu-btn',
  NetworkListItem = 'network-list-item',
  ChangeNetworkAction = 'settings-change-network',
  SwitchAccount = 'switch-account',
  CurrentNetwork = 'current-network',
  CreateAccountBtn = 'create-account-button',
  CurrentAccountDisplayName = 'current-account-display-name',
  ViewSecretKeyListItem = 'settings-view-secret-key',
  CopyKeyToClipboardBtn = 'copy-key-to-clipboard-btn',
  SignOutListItem = 'settings-sign-out',
  SignOutConfirmHasBackupCheckbox = 'sign-out-confirm-has-backup-checkbox',
  BtnSignOutReturnToHomeScreen = 'btn-sign-out-return-to-home-screen',
  BtnSignOutActuallyDeleteWallet = 'btn-sign-out-actually-delete-wallet',
  LockListItem = 'settings-lock',
  AccountIndex = 'switch-account-item-[index]',
  EnterPasswordInput = 'password-input',
  UnlockWalletBtn = 'unlock-wallet-btn',
  BtnAddNetwork = 'btn-add-network',
}
