export enum SendCryptoAssetSelectors {
  AmountFieldInput = 'amount-field-input',
  AmountFieldInputErrorLabel = 'amount-field-input-error-label',
  ConfirmationDetails = 'confirmation-details',
  ConfirmSendTxBtn = 'confirm-send-tx-btn',
  ConfirmationDetailsAmountAndSymbol = 'confirmation-details-amount-and-symbol',
  ConfirmationDetailsRecipient = 'confirmation-details-recipient',
  ConfirmationDetailsAssetValue = 'confirmation-details-asset-value',
  ConfirmationDetailsFee = 'confirmation-details-fee',
  ConfirmationDetailsMemo = 'confirmation-details-memo',
  ConfirmationDetailText = 'confirmation-detail-text',
  FormFieldInputErrorLabel = 'form-field-input-error-label',
  MemoFieldInput = 'memo-field-input',
  PreviewSendTxBtn = 'preview-send-tx-btn',
  RecipientChooseAccountButton = 'recipient-choose-account-button',
  RecipientFieldInput = 'recipient-field-input',
  RecipientBnsAddressLabel = 'recipient-bns-address-label',
  RecipientBnsAddressInfoIcon = 'recipient-bns-address-info-icon',
  RecipientBnsAddressCopyToClipboard = 'recipient-bns-address-copy-to-clipboard',
  SendForm = 'send-form',
  SendMaxBtn = 'send-max-btn',
}
