declare const EXT_ENV: string;
declare const NODE_ENV: string;
declare const SEGMENT_KEY: string;
declare const STATS_URL: string;
declare const COMMIT_SHA: string;
declare const VERSION: string;
declare const BRANCH: string;
declare const BRANCH_NAME: string;
// TESTING ENV VARIABLES
declare const GITHUB_REF: string;
declare const GITHUB_HEAD_REF: string;
declare const GITHUB_REF_NAME: string;
