name: All checks pass
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read

    steps:
      - uses: wechuli/allcheckspassed@v1
