name: Check signed commits
on: pull_request_target
permissions:
  contents: read
  pull-requests: write

jobs:
  check-signed-commits:
    name: Check signed commits
    runs-on: ubuntu-latest
    steps:
      - name: Check signed commits
        uses: 1Password/check-signed-commits-action@v1
